Controllers/CFERecordController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SicemOperation.Data;
using SicemOperation.Entities;
using SicemOperation.Models;
using SicemOperation.Models.DTO.CFE;

namespace SicemOperation.Controllers;

[Authorize]
[Route("/[controller]")]
public class CFERecordController : Controller
{
    private readonly ILogger<CFERecordController> _logger;
    private readonly SicemOperationContext sicemOperationContext;
    
    public CFERecordController(ILogger<CFERecordController> logger, SicemOperationContext sicemOperationContext)
    {
        this._logger = logger;
        this.sicemOperationContext = sicemOperationContext;
    }

    public IActionResult Index()
    {
        return View();
    }

    [Route("Consumo")]
    public IActionResult Consumo([FromQuery] int? af, [FromQuery] int? mf, [FromQuery] int? medidorId)
    {
        // * get the catalog of medidores
        var medidoresListItems = this.sicemOperationContext.CFEMedidores.Select(item => new SelectListItem(item.NumMedidor, item.Id.ToString())).ToList();

        // * get the period of the consumo
        var period = DateTime.Now;
        try
        {
            if(af != null && mf != null)
            {
                period = new DateTime(af.Value, mf.Value, 1);
            }
        }
        catch (System.Exception)
        {
            ViewBag.ErrorMessage = "El periodo seleccionado no es válido.";
            return View( new ConsumoDTO()
                {
                    Af = period.Year,
                    Mf = period.Month,
                    MedidoresListItems = medidoresListItems
                }
            );
        }

        // * check if the medidor is passed
        CFEMedidor? medidor = null;
        if(medidorId != null)
        {
            medidor = this.sicemOperationContext.CFEMedidores.Find(medidorId);
        }

        // * attempt to get the consume of the medidor in the target period
        CFEConsumo? cFEConsumo = null;
        if(medidor != null)
        {
            cFEConsumo = this.sicemOperationContext.CFEConsumos.FirstOrDefault( item => item.IdMedidor == medidor.Id && item.Af == period.Year && item.Mf == period.Month);
        }

        if(cFEConsumo == null & medidor != null)
        {
            cFEConsumo = new CFEConsumo {
                IdMedidor = medidor!.Id,
                FechaInicio = new DateTime(period.Year, period.Month, 1),
                FechaFin = new DateTime(period.Year, period.Month, DateTime.DaysInMonth(period.Year, period.Month)),
                Consumo = 0,
                Importe = 0,
                Demanda = 0,
                Af = period.Year,
                Mf = period.Month,
                Kvarh = 0,
                FpPorc = 0,
                FpMon = 0,
                DapMon = 0,
            };
        }

        // * prepare the view
        var record = new ConsumoDTO()
        {
            Af = period.Year,
            Mf = period.Month,
            MedidoresListItems = medidoresListItems,
            Medidor = medidor,
            Consumo = cFEConsumo
        };
        ViewBag.FormTitle = "Registrar Consumo del Periodo " + period.ToString("MMMM yyyy") + " para el Medidor " + (medidor != null ? medidor.NumMedidor : "No seleccionado");
        return View(record);
    }

    [HttpPost("store")]
    public IActionResult StoreConsumo([FromForm] ConsumoDTO consumoDTO)
    {
        // if(!ModelState.IsValid)
        // {
        //     return View("Consumo", consumoDTO);
        // }

        Console.WriteLine("ConsumoDTO: {0}", consumoDTO);
        return RedirectToAction("Consumo", new { af = consumoDTO.Af, mf = consumoDTO.Mf, medidorId = consumoDTO.MedidorId });
    }


}

Controllers/CFETarifaController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SicemOperation.Data;
using SicemOperation.Entities;

namespace SicemOperation.Controllers;

[Authorize]
[Route("/CFERecord/Catalogos/[controller]")]
public class CFETarifaController : Controller
{
    private readonly ILogger<CFETarifaController> _logger;
    private readonly SicemOperationContext sicemOperationContext;
    
    public CFETarifaController(ILogger<CFETarifaController> logger, SicemOperationContext sicemOperationContext)
    {
        this._logger = logger;
        this.sicemOperationContext = sicemOperationContext;
    }

    
    public IActionResult Index()
    {
        var tarifas = sicemOperationContext.CFETarifas.ToList();
        return View(tarifas);
    }

    [HttpGet("create")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Nombre,Inactivo")] CFETarifa cfeTarifa)
    {
        if (ModelState.IsValid)
        {
            sicemOperationContext.CFETarifas.Add(cfeTarifa);
            await sicemOperationContext.SaveChangesAsync();
            return RedirectToAction("TarifasIndex");
        }
        return View(cfeTarifa);
    }

    [HttpGet("edit/{id}")]
    public async Task<IActionResult> Edit([FromRoute] int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cfeTarifa = await this.sicemOperationContext.CFETarifas.FindAsync(id);
        if (cfeTarifa == null)
        {
            return NotFound();
        }

        return View(cfeTarifa);
    }

    [HttpPost("edit/{id}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit([FromRoute] int id, [Bind("Id,Nombre,Inactivo")] CFETarifa cfeTarifa)
    {
        if (id != cfeTarifa.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                this.sicemOperationContext.CFETarifas.Update(cfeTarifa);
                await this.sicemOperationContext.SaveChangesAsync();
            }
            catch (Exception)
            {
                if (!CFETarifaExists(cfeTarifa.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("TarifasIndex");
        }
        
        return View(cfeTarifa);
    }

    private bool CFETarifaExists(int id)
    {
        return this.sicemOperationContext.CFETarifas.Any(e => e.Id == id);
    }

}

Controllers/CFEZonaController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using SicemOperation.Data;
using SicemOperation.Entities;
using SicemOperation.Models;
using SicemOperation.Services;

namespace SicemOperation.Controllers;

[Authorize]
[Route("/catalogos/[controller]")]
public class CFEZonaController : Controller
{
    private readonly ILogger<CFEZonaController> _logger;
    private readonly SicemOperationContext sicemOperationContext;
    
    public CFEZonaController(ILogger<CFEZonaController> logger, SicemOperationContext sicemOperationContext)
    {
        this._logger = logger;
        this.sicemOperationContext = sicemOperationContext;
    }

    
    public IActionResult Index()
    {
        var zonas = sicemOperationContext.CFEZonas.ToList();
        return View(zonas);
    }

    [HttpGet("create")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Zona")] CFEZona cfeZona)
    {
        if (ModelState.IsValid)
        {
            this.sicemOperationContext.CFEZonas.Add(cfeZona);
            await sicemOperationContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        return View(cfeZona);
    }

    [HttpGet("edit/{id}")]
    public async Task<IActionResult> Edit([FromRoute] int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cfeZona = await this.sicemOperationContext.CFEZonas.FindAsync(id);
        if (cfeZona == null)
        {
            return NotFound();
        }

        return View(cfeZona);
    }

    [HttpPost("edit/{id}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit([FromRoute] int id, [Bind("Id,Zona")] CFEZona cfeZona)
    {
        if (id != cfeZona.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                this.sicemOperationContext.CFEZonas.Update(cfeZona);
                await this.sicemOperationContext.SaveChangesAsync();
            }
            catch (Exception)
            {
                if (!CFEZonaExists(cfeZona.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(cfeZona);
    }

    private bool CFEZonaExists(int id)
    {
        return sicemOperationContext.CFEZonas.Any(e => e.Id == id);
    }

}

Controllers/RecordController.cs
using System.Diagnostics;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.VisualBasic;
using SicemOperation.Models;
using SicemOperation.Services;

namespace SicemOperation.Controllers;

[Authorize]
public class RecordController : Controller
{
    private readonly ILogger<RecordController> _logger;
    private readonly IncidenceService incidenceService;
    private readonly ICompositeViewEngine viewEngine;

    public RecordController(ILogger<RecordController> logger, IncidenceService incidenceService, ICompositeViewEngine viewEngine) {
        this._logger = logger;
        this.incidenceService = incidenceService;
        this.viewEngine = viewEngine;
    }

    public IActionResult Index([FromQuery] int? year, [FromQuery] int? month) {

        DateTime targetDate;

        // Get the current date
        if( year != null && month != null){
            targetDate = new DateTime(year.Value, month.Value, 1);
        }else{
            targetDate = DateTime.Today;
        }
        
        ViewBag.TargetDate = targetDate.ToString("yyyy-MM-ddTHH:mm:ss");

        return View();
    }

    public IActionResult NewRecord() {
        return View(new NewRecordRequest());
    }

    [HttpPost]
    public IActionResult NewRecord(NewRecordRequest request) {
        if(ModelState.IsValid){
            this.incidenceService.RegisterIncidence(request);
            return RedirectToAction("Index");
        }

        ViewBag.Message = "Datos no validos, verifique e intente de nuevo.";
        ViewBag.MessageClass = "alert-danger";
        return View();
    }


    [Route("/record/testing/fake-data")]
    public IActionResult FakeDate([FromQuery] int year, [FromQuery] int c ){
        
        for( int i = 1; i<=12; i++){
            this.incidenceService.FakeData(year, i, c );
        }

        return Ok( new {
            Message = "Done",
            Year = year,
            Count = c
        });
    }


    public IActionResult ShowRecordsDay(int year, int month, int day){
        ViewBag.DateTarget = new DateTime(year, month, day);
        var incidents = this.incidenceService.GetIncidentsByDate(ViewBag.DateTarget);
        return View("RecordsDay");
    }

    [Route("/record/resume-chart")]
    [HttpGet]
    public IActionResult ResumeChart([FromQuery] int year, [FromQuery] int month){
        var incidentsGrid = this.incidenceService.IncidentsTypesGetIncidentsGrid(year, month);

        var groupedData = new List<dynamic>();
        foreach(var gp in incidentsGrid.Elements.GroupBy(item => item.Group)){
            var _days = new int[incidentsGrid.TotalDays];
            foreach(var _data in gp){
                for(int i=0; i< _data.Data.Count(); i++){
                    _days[i] += _data.Data.ElementAt(i);
                }
            }
            groupedData.Add( new {
                Label = gp.Key.Substring(1,2),
                Days = _days,
            });
        }   

        var Labels = new List<string>();
        for(int i=0; i<incidentsGrid.TotalDays;i++){
            Labels.Add((i+1).ToString());
        }
        var SeriesData = groupedData.Select( item => item.Days);
        

        // // prepare the response
        // var SeriesData = new List<dynamic>();
        // for(int i=0; i<incidentsGrid.TotalDays; i++){
        //     var arrDays = new int[groupedData.Count];
        //     for(int j=0; j<groupedData.Count; j++){
        //         arrDays[j] = groupedData.ElementAt(j).Days[i];
        //     }
        //     SeriesData.Add(arrDays);
        // };

        return Ok(
            new {
                // Labels = groupedData.Select(item => item.Label),
                Labels,
                Series = SeriesData
            }
        );

    }

    #region partial views

    public ActionResult GetIncidentGrid(int year, int month ){

        // * get the incidents of the month
        try {
            var incidentsGrid = this.incidenceService.IncidentsTypesGetIncidentsGrid(year, month);
            return PartialView("~/Views/Record/Partials/IncidentGrid.cshtml", incidentsGrid);

        }catch(Exception err){
            this._logger.LogError(err, "Fail at get the incident grid data");
            ViewData["ErrorTitle"] = "Error resumen incidencias por mes";
            ViewData["ErrorMessage"] = "Hubo un error al obtener el resumen de incidencias, intente de nuevo o comuníquese con un administrador.";
            return PartialView("~/Views/Shared/ErrorAlert.cshtml", new ErrorViewModel());
        }
    }

    #endregion

}

Views/Shared/ErrorAlert.cshtml
<div class="alert alert-danger d-flex align-items-center" role="alert">

    <svg class="mr-3" xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24">
        <path fill="currentColor" d="M12 17q.425 0 .713-.288T13 16t-.288-.712T12 15t-.712.288T11 16t.288.713T12 17m-1-4h2V7h-2zm1 9q-2.075 0-3.9-.788t-3.175-2.137T2.788 15.9T2 12t.788-3.9t2.137-3.175T8.1 2.788T12 2t3.9.788t3.175 2.137T21.213 8.1T22 12t-.788 3.9t-2.137 3.175t-3.175 2.138T12 22"/>
    </svg>
    
    <div class="d-flex flex-column">
        @if(ViewData["ErrorTitle"] != null){
            <div class="text-bold" style="font-size: 1.3rem; line-height: 1.5rem;">@ViewData["ErrorTitle"]</div>
        }
        
        @if(ViewData["ErrorMessage"] != null){
            <div class="mt-2" style="font-size: 1rem;">@ViewData["ErrorMessage"]</div>
        }
    </div>
</div>

Views/Shared/NotificationPanel.cshtml
@model ICollection<dynamic>
@{
    ViewData["Title"] = "Error";
}

<li class="nav-item dropdown notification">
    <a class="nav-link nav-icons" href="#" id="navbarDropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-fw fa-bell"></i>
        <span class="indicator @(Model.Any()?"":"d-none")"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-right notification-dropdown">
        @if(Model.Any()){
            <li>
                <div class="notification-title"> Notificaciones</div>
                <div class="notification-list">
                    <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action active">
                            <div class="notification-info">
                                <div class="notification-list-user-img"><img src="/images/avatar-2.jpg" alt="" class="user-avatar-md rounded-circle"></div>
                                <div class="notification-list-user-block"><span class="notification-list-user-name">Jeremy Rakestraw</span>accepted your invitation to join the team.
                                    <div class="notification-date">2 min ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action">
                            <div class="notification-info">
                                <div class="notification-list-user-img">
                                    <img src="/images/avatar-3.jpg" alt="" class="user-avatar-md rounded-circle"></div>
                                <div class="notification-list-user-block">
                                    <span class="notification-list-user-name">
                                    John Abraham</span>is now following you
                                    <div class="notification-date">2 days ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action">
                            <div class="notification-info">
                                <div class="notification-list-user-img"><img src="/images/avatar-4.jpg" alt="" class="user-avatar-md rounded-circle"></div>
                                <div class="notification-list-user-block"><span class="notification-list-user-name">Monaan Pechi</span> is watching your main repository
                                    <div class="notification-date">2 min ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action">
                            <div class="notification-info">
                                <div class="notification-list-user-img"><img src="/images/avatar-5.jpg" alt="" class="user-avatar-md rounded-circle"></div>
                                <div class="notification-list-user-block"><span class="notification-list-user-name">Jessica Caruso</span>accepted your invitation to join the team.
                                    <div class="notification-date">2 min ago</div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </li>
            <li>
                <div class="list-footer">
                    <a href="#" class="text-white">Mostrar todas las notificaciones</a>
                </div>
            </li>
        }else{
            <li>
                <div class="px-2 py-4 text-center text-black-50">No hay notificaciones</div>
            </li>
        }
    </ul>
</li>

Views/Shared/PageHeader.cshtml
@model IEnumerable<dynamic>

<div class="row bg-white pt-3 pb-2 mt-2 shadow-sm rounded">
    <div class="col-6">
        <h1 class="breadcrumb-title text-uppercase text-gray fa-1x">@ViewData["PageTitle"]</h1>
    </div>

    @if(Model.Any()){
    <div class="col-6 page-breadcrumb">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb pt-0 justify-content-end" style="border:none;">
                @foreach(var element in Model){
                    @if(string.IsNullOrEmpty(element.Route)){
                    <li class="breadcrumb-item active" aria-current="page">@element.Title</li>
                    }else{
                    <li class="breadcrumb-item">
                        <a href="@element.Route" class="breadcrumb-link">@element.Title</a>
                    </li>
                    }
                }
            </ol>
        </nav>
    </div>
    }
</div>

Views/Shared/SideBarMenu.cshtml
<div class="nav-left-sidebar sidebar-dark">
    <div class="menu-list">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="d-xl-none d-lg-none" href="#">Dashboard</a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav flex-column">
                    <li class="nav-divider"> Menu </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            <i class="fa fa-fw fa-user-circle"></i>Dashboard
                            <span class="badge badge-success">6</span>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-2" aria-controls="submenu-2"><i class="fab fa-fw fa-wpforms"></i>Capturas</a>
                        <div id="submenu-2" class="collapse submenu" style="">
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Record" asp-action="Index">Historial Capturas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Record" asp-action="NewRecord">Registrar Captura</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-3" aria-controls="submenu-3">
                            <i class="fab fa fa-bolt"></i>
                            <span>CFE</span>
                        </a>
                        <div id="submenu-3" class="collapse submenu" style="">
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Record" asp-action="Index">Historial Consumo</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Record" asp-action="Index">Registrar Consumo</a>
                                </li>
                                
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="CFERecord" asp-action="CatalogsIndex">Catalogos</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="CFEMedidor" asp-action="Index">Catalogo Medidores</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="CFEProceso" asp-action="Index">Catalogo Procesos</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="CFEZona" asp-action="Index">Catalogo Zonas</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="CFERecord" asp-action="TarifasIndex">Catalogo Tarifas</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-controller="Home" asp-action="Privacy">
                            <i class="fa fa-info-circle"></i>Informacion
                            <span class="badge badge-success">6</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

Views/Shared/SidebarMenu2.cshtml
<div class="sidebar__menu-group">
    <ul class="sidebar_nav">
        <li class="">
            <a asp-controller="Home" asp-action="Index">
                <span class="nav-icon uil uil-create-dashboard"></span>
                <span class="menu-text">Inicio</span>
            </a>
        </li>

        <li class="has-child">
            <a href="#" class="">
                <span class="nav-icon uil uil-book-open"></span>
                <span class="menu-text">Capturas</span>
                <span class="toggle-icon"></span>
            </a>
            <ul>
                <li class="">
                    <a class="nav-link" asp-controller="Record" asp-action="Index">Historial Capturas</a>
                </li>
                <li class="">
                    <a class="nav-link" asp-controller="Record" asp-action="NewRecord">Registrar Captura</a>
                </li>
            </ul>
        </li>

        <li class="has-child ">
            <a href="#" class="">
                <span class="nav-icon las la-bolt"></span>
                <span class="menu-text">CFE</span>
                <span class="toggle-icon"></span>
            </a>
            <ul>
                <li>
                    <a class="nav-link" asp-controller="Record" asp-action="Index">Historial Consumo</a>
                </li>
                <li>
                    <a class="nav-link" asp-controller="CFERecord" asp-action="Consumo">Registrar Consumo</a>
                </li>

                <li class="menu-title mt-15" style="padding-left: 1rem;">
                    <span>Catalogos</span>
                </li>
                <li>
                    <a class="nav-link" asp-controller="CFEMedidor" asp-action="Index">Catalogo Medidores</a>
                </li>

                <li>
                    <a class="nav-link" asp-controller="CFEProceso" asp-action="Index">Catalogo Procesos</a>
                </li>

                <li>
                    <a class="nav-link" asp-controller="CFEZona" asp-action="Index">Catalogo Zonas</a>
                </li>

                <li>
                    <a class="nav-link" asp-controller="CFETarifa" asp-action="Index">Catalogo Tarifas</a>
                </li>

            </ul>
        </li>

        <li class="">
            <a asp-controller="Home" asp-action="Privacy">
                <span class="nav-icon uil uil-sign-out-alt"></span>
                <span class="menu-text">Informacion</span>
            </a>
        </li>


        @*
        <li class="menu-title mt-30">
            <span>Subtitle</span>
        </li>
        <li class="has-child">
            <a href="#" class="">
                <span class="nav-icon uil uil-envelope"></span>
                <span class="menu-text">Email</span>
                <span class="toggle-icon"></span>
            </a>
            <ul>
                <li class="">
                    <a href="inbox.html">Inbox</a>
                </li>
                <li class="">
                    <a href="read-email.html">Read Email</a>
                </li>
            </ul>
        </li>
        *@

    </ul>
</div>

Views/Shared/SiderbarMenu2.cshtml
<div class="sidebar__menu-group">
    <ul class="sidebar_nav">
        <li class="">
            <a asp-controller="Home" asp-action="Index">
                <span class="nav-icon uil uil-create-dashboard"></span>
                <span class="menu-text">Inicio</span>
            </a>
        </li>

        <li class="has-child">
            <a href="#" class="">
                <span class="nav-icon uil uil-book-open"></span>
                <span class="menu-text">Capturas</span>
                <span class="toggle-icon"></span>
            </a>
            <ul>
                <li class="">
                    <a class="nav-link" asp-controller="Record" asp-action="Index">Historial Capturas</a>
                </li>
                <li class="">
                    <a class="nav-link" asp-controller="Record" asp-action="NewRecord">Registrar Captura</a>
                </li>
            </ul>
        </li>

        <li class="">
            <a asp-controller="Home" asp-action="Privacy">
                <span class="nav-icon uil uil-sign-out-alt"></span>
                <span class="menu-text">Informacion</span>
            </a>
        </li>


        @*
        <li class="menu-title mt-30">
            <span>Subtitle</span>
        </li>
        <li class="has-child">
            <a href="#" class="">
                <span class="nav-icon uil uil-envelope"></span>
                <span class="menu-text">Email</span>
                <span class="toggle-icon"></span>
            </a>
            <ul>
                <li class="">
                    <a href="inbox.html">Inbox</a>
                </li>
                <li class="">
                    <a href="read-email.html">Read Email</a>
                </li>
            </ul>
        </li>
        *@

    </ul>
</div>

Views/Shared/TopMenu.cshtml
<div class="sidebar__menu-group">
    <ul class="sidebar_nav">
        <li class="">
            <a asp-controller="Home" asp-action="Index">
                <span class="nav-icon uil uil-create-dashboard"></span>
                <span class="menu-text">Inicio</span>
            </a>
        </li>

        <li class="has-child">
            <a href="#" class="">
                <span class="nav-icon uil uil-book-open"></span>
                <span class="menu-text">Capturas</span>
                <span class="toggle-icon"></span>
            </a>
            <ul>
                <li class="">
                    <a class="nav-link" asp-controller="Record" asp-action="Index">Historial Capturas</a>
                </li>
                <li class="">
                    <a class="nav-link" asp-controller="Record" asp-action="NewRecord">Registrar Captura</a>
                </li>
            </ul>
        </li>

        <li class="has-child ">
            <a href="#" class="">
                <span class="nav-icon las la-bolt"></span>
                <span class="menu-text">CFE</span>
                <span class="toggle-icon"></span>
            </a>
            <ul>
                <li class="">
                    <a class="nav-link" asp-controller="Record" asp-action="Index">Historial Consumo</a>
                </li>
                <li class="">
                    <a class="nav-link" asp-controller="Record" asp-action="Index">Registrar Consumo</a>
                </li>
                <li class="">
                    <a class="nav-link" asp-controller="CFERecord" asp-action="CatalogsIndex">Catalogos</a>
                </li>
            </ul>
        </li>

        <li class="">
            <a asp-controller="Home" asp-action="Privacy">
                <span class="nav-icon uil uil-sign-out-alt"></span>
                <span class="menu-text">Informacion</span>
            </a>
        </li>


        @*
        <li class="menu-title mt-30">
            <span>Subtitle</span>
        </li>
        <li class="has-child">
            <a href="#" class="">
                <span class="nav-icon uil uil-envelope"></span>
                <span class="menu-text">Email</span>
                <span class="toggle-icon"></span>
            </a>
            <ul>
                <li class="">
                    <a href="inbox.html">Inbox</a>
                </li>
                <li class="">
                    <a href="read-email.html">Read Email</a>
                </li>
            </ul>
        </li>
        *@

    </ul>
</div>