Controllers/CFEMedidorController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SicemOperation.Data;
using SicemOperation.Entities;

namespace SicemOperation.Controllers;

[Authorize]
[Route("/CFERecord/Catalogos/[controller]")]
public class CFEMedidorController : Controller
{
    private readonly ILogger<CFEMedidorController> _logger;
    private readonly SicemOperationContext sicemOperationContext;
    
    public CFEMedidorController(ILogger<CFEMedidorController> logger, SicemOperationContext sicemOperationContext)
    {
        this._logger = logger;
        this.sicemOperationContext = sicemOperationContext;
    }

    
    public IActionResult Index()
    {
        var medidores = this.sicemOperationContext.CFEMedidores
            .Include(m => m.Organismo)
            .Include(m => m.Tarifa)
            .Include(m => m.Proceso)
            .Include(m => m.Zona)
            .ToList();

        return View(medidores);
    }

    [HttpGet("create")]
    public IActionResult Create()
    {
        LoadSelectListCatalogs();
        return View();
    }

    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromBody] CFEMedidor cfeMedidor)
    {
        if (ModelState.IsValid)
        {
            this.sicemOperationContext.Add(cfeMedidor);
            await this.sicemOperationContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        LoadSelectListCatalogs();
        return View(cfeMedidor);
    }

    [HttpGet("edit/{id}")]
    public async Task<IActionResult> Edit([FromRoute] int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cfeMedidor = await this.sicemOperationContext.CFEMedidores.FindAsync(id);
        if (cfeMedidor == null)
        {
            return NotFound();
        }

        LoadSelectListCatalogs();
        return View(cfeMedidor);
    }

    [HttpPost("edit/{id}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit([FromRoute] int id, [FromBody] CFEMedidor cFEMedidor)
    {
        if (id != cFEMedidor.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                this.sicemOperationContext.Update(cFEMedidor);
                await this.sicemOperationContext.SaveChangesAsync();
            }
            catch (Exception)
            {
                if (!CFEMedidorExists(cFEMedidor.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        
        LoadSelectListCatalogs();
        return View(cFEMedidor);
    }


    private void LoadSelectListCatalogs()
    {
        ViewBag.Organismos = this.sicemOperationContext.Organismos.Select(o => new SelectListItem { Value = o.Id.ToString(), Text = o.Nombre }).ToList();
        ViewBag.Tarifas = this.sicemOperationContext.CFETarifas.Where(e => e.Inactivo != true).Select(o => new SelectListItem { Value = o.Id.ToString(), Text = o.Nombre }).ToList();
        ViewBag.Procesos = this.sicemOperationContext.CFEProcesos.Select(o => new SelectListItem { Value = o.Id.ToString(), Text = o.Proceso }).ToList();
        ViewBag.Zonas = this.sicemOperationContext.CFEZonas.Select(o => new SelectListItem { Value = o.Id.ToString(), Text = o.Zona }).ToList();
    }

    private bool CFEMedidorExists(int id)
    {
        return sicemOperationContext.CFEMedidores.Any(e => e.Id == id);
    }

}

Controllers/CFERecordController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SicemOperation.Data;
using SicemOperation.Entities;
using SicemOperation.Models;
using SicemOperation.Models.DTO.CFE;

namespace SicemOperation.Controllers;

[Authorize]
[Route("/[controller]")]
public class CFERecordController : Controller
{
    private readonly ILogger<CFERecordController> _logger;
    private readonly SicemOperationContext sicemOperationContext;
    
    public CFERecordController(ILogger<CFERecordController> logger, SicemOperationContext sicemOperationContext)
    {
        this._logger = logger;
        this.sicemOperationContext = sicemOperationContext;
    }

    public IActionResult Index()
    {
        return View();
    }

    [Route("Consumo")]
    public IActionResult Consumo([FromQuery] int? af, [FromQuery] int? mf, [FromQuery] int? medidorId)
    {
        // * get the catalog of medidores
        var medidoresListItems = this.sicemOperationContext.CFEMedidores.Select(item => new SelectListItem(item.NumMedidor, item.Id.ToString())).ToList();

        // * get the period of the consumo
        var period = DateTime.Now;
        try
        {
            if(af != null && mf != null)
            {
                period = new DateTime(af.Value, mf.Value, 1);
            }
        }
        catch (System.Exception)
        {
            ViewBag.ErrorMessage = "El periodo seleccionado no es válido.";
            return View( new ConsumoDTO()
                {
                    Af = period.Year,
                    Mf = period.Month,
                    MedidoresListItems = medidoresListItems
                }
            );
        }

        // * check if the medidor is passed
        CFEMedidor? medidor = null;
        if(medidorId != null)
        {
            medidor = this.sicemOperationContext.CFEMedidores.Find(medidorId);
        }

        // * attempt to get the consume of the medidor in the target period
        CFEConsumo? cFEConsumo = null;
        if(medidor != null)
        {
            cFEConsumo = this.sicemOperationContext.CFEConsumos.FirstOrDefault( item => item.IdMedidor == medidor.Id && item.Af == period.Year && item.Mf == period.Month);
        }

        if(cFEConsumo == null & medidor != null)
        {
            cFEConsumo = new CFEConsumo {
                IdMedidor = medidor!.Id,
                FechaInicio = new DateTime(period.Year, period.Month, 1),
                FechaFin = new DateTime(period.Year, period.Month, DateTime.DaysInMonth(period.Year, period.Month)),
                Consumo = 0,
                Importe = 0,
                Demanda = 0,
                Af = period.Year,
                Mf = period.Month,
                Kvarh = 0,
                FpPorc = 0,
                FpMon = 0,
                DapMon = 0,
            };
        }

        // * prepare the view
        var record = new ConsumoDTO()
        {
            Af = period.Year,
            Mf = period.Month,
            MedidoresListItems = medidoresListItems,
            Medidor = medidor,
            Consumo = cFEConsumo
        };
        ViewBag.FormTitle = "Registrar Consumo del Periodo " + period.ToString("MMMM yyyy") + " para el Medidor " + (medidor != null ? medidor.NumMedidor : "No seleccionado");
        return View(record);
    }

    [HttpPost("store")]
    public IActionResult StoreConsumo([FromForm] ConsumoDTO consumoDTO)
    {
        // if(!ModelState.IsValid)
        // {
        //     return View("Consumo", consumoDTO);
        // }

        Console.WriteLine("ConsumoDTO: {0}", consumoDTO);
        return RedirectToAction("Consumo", new { af = consumoDTO.Af, mf = consumoDTO.Mf, medidorId = consumoDTO.MedidorId });
    }


}

Controllers/CFETarifaController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SicemOperation.Data;
using SicemOperation.Entities;

namespace SicemOperation.Controllers;

[Authorize]
[Route("/CFERecord/Catalogos/[controller]")]
public class CFETarifaController : Controller
{
    private readonly ILogger<CFETarifaController> _logger;
    private readonly SicemOperationContext sicemOperationContext;
    
    public CFETarifaController(ILogger<CFETarifaController> logger, SicemOperationContext sicemOperationContext)
    {
        this._logger = logger;
        this.sicemOperationContext = sicemOperationContext;
    }

    
    public IActionResult Index()
    {
        var tarifas = sicemOperationContext.CFETarifas.ToList();
        return View(tarifas);
    }

    [HttpGet("create")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Nombre,Inactivo")] CFETarifa cfeTarifa)
    {
        if (ModelState.IsValid)
        {
            sicemOperationContext.CFETarifas.Add(cfeTarifa);
            await sicemOperationContext.SaveChangesAsync();
            return RedirectToAction("TarifasIndex");
        }
        return View(cfeTarifa);
    }

    [HttpGet("edit/{id}")]
    public async Task<IActionResult> Edit([FromRoute] int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cfeTarifa = await this.sicemOperationContext.CFETarifas.FindAsync(id);
        if (cfeTarifa == null)
        {
            return NotFound();
        }

        return View(cfeTarifa);
    }

    [HttpPost("edit/{id}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit([FromRoute] int id, [Bind("Id,Nombre,Inactivo")] CFETarifa cfeTarifa)
    {
        if (id != cfeTarifa.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                this.sicemOperationContext.CFETarifas.Update(cfeTarifa);
                await this.sicemOperationContext.SaveChangesAsync();
            }
            catch (Exception)
            {
                if (!CFETarifaExists(cfeTarifa.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("TarifasIndex");
        }
        
        return View(cfeTarifa);
    }

    private bool CFETarifaExists(int id)
    {
        return this.sicemOperationContext.CFETarifas.Any(e => e.Id == id);
    }

}

Controllers/CFEZonaController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using SicemOperation.Data;
using SicemOperation.Entities;
using SicemOperation.Models;
using SicemOperation.Services;

namespace SicemOperation.Controllers;

[Authorize]
[Route("/catalogos/[controller]")]
public class CFEZonaController : Controller
{
    private readonly ILogger<CFEZonaController> _logger;
    private readonly SicemOperationContext sicemOperationContext;
    
    public CFEZonaController(ILogger<CFEZonaController> logger, SicemOperationContext sicemOperationContext)
    {
        this._logger = logger;
        this.sicemOperationContext = sicemOperationContext;
    }

    
    public IActionResult Index()
    {
        var zonas = sicemOperationContext.CFEZonas.ToList();
        return View(zonas);
    }

    [HttpGet("create")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Zona")] CFEZona cfeZona)
    {
        if (ModelState.IsValid)
        {
            this.sicemOperationContext.CFEZonas.Add(cfeZona);
            await sicemOperationContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        return View(cfeZona);
    }

    [HttpGet("edit/{id}")]
    public async Task<IActionResult> Edit([FromRoute] int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cfeZona = await this.sicemOperationContext.CFEZonas.FindAsync(id);
        if (cfeZona == null)
        {
            return NotFound();
        }

        return View(cfeZona);
    }

    [HttpPost("edit/{id}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit([FromRoute] int id, [Bind("Id,Zona")] CFEZona cfeZona)
    {
        if (id != cfeZona.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                this.sicemOperationContext.CFEZonas.Update(cfeZona);
                await this.sicemOperationContext.SaveChangesAsync();
            }
            catch (Exception)
            {
                if (!CFEZonaExists(cfeZona.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(cfeZona);
    }

    private bool CFEZonaExists(int id)
    {
        return sicemOperationContext.CFEZonas.Any(e => e.Id == id);
    }

}

Views/CFERecord/CatalogsIndex.cshtml
@{
    ViewData["Title"] = "Catalogos CFE";
    ViewData["PageTitle"] = "Catalogos CFE ";
    var breadcrumbElements = new List<dynamic>();
    breadcrumbElements.Add(new { Title = "CFE Catalogos", Route ="" });
}
<partial name="PageHeader" model="@breadcrumbElements" />


<ul class="nav">
    <li class="nav-item">
        <a class="nav-link" asp-controller="CFETarifa" asp-action="Index">Catalogo Tarifas</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="CFEZona" asp-action="Index">Catalogo Zonas</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" asp-controller="CFEProceso" asp-action="Index">Catalogo Procesos</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" asp-controller="CFEMedidor" asp-action="Index">Catalogo Medidores</a>
    </li>
</ul>

Views/CFERecord/Consumo.cshtml
@model SicemOperation.Models.DTO.CFE.ConsumoDTO
@{
    ViewData["Title"] = "CFE Registro Consumo";
    ViewData["PageTitle"] = "CFE Registro Consumo";
    var breadcrumbElements = new List<dynamic>();
    breadcrumbElements.Add(new { Title = "CFE Consumos", Route = "" });
}
@section styles
{
    <link rel="stylesheet" href="/assets/vendor_assets/css/select2.min.css">
}

<partial name="PageHeader" model="@breadcrumbElements" />

<div class="row mt-3">
    <div class="col-12">
        <div class="card card-Vertical card-default card-md mb-4">
            <div class="card-body pb-md-30">
                <div class="Vertical-form">
                    <form asp-controller="CFERecord" asp-action="Consumo" method="get">
                        <div class="form-group row">
                            <div class="col-2">
                                <label asp-for="Af" class="color-dark fs-14 fw-500 align-center"></label>
                                <input asp-for="Af" type="number" class="form-control ip-light radius-xs b-light px-15" placeholder="Año" />
                            </div>
                            <div class="col-2">
                                <label asp-for="Mf" class="color-dark fs-14 fw-500 align-center"></label>
                                <input asp-for="Mf" type="number" class="form-control ip-light radius-xs b-light px-15" placeholder="Año" />
                            </div>
                            <div class="col-3">
                                <label asp-for="MedidorId" class="il-gray fs-14 fw-500 align-center"></label>
                                <select asp-for="MedidorId" asp-items="@Model.MedidoresListItems" class="form-control ip-light radius-xs b-light px-15 select2"></select>
                            </div>
                            <div class="col-2 d-flex justify-content-center mt-2">
                                <button type="submit" class="btn btn-primary btn-sm btn-squared text-capitalize px-30">Consultar</button>
                            </div>
                        </div>
                    </form>
                    @if(ViewBag.ErrorMessage != null)
                    {
                        <div class=" alert alert-danger mt-2" role="alert">
                            <div class="alert-content">
                                <p>@ViewBag.ErrorMessage</p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

    @if(Model.Consumo != null)
    {
        <div class="col-12">
            <div class="card card-Vertical card-default card-md mb-4">
                <div class="card-header">
                    <h5 id="#form-title" class="text-uppercase">@ViewBag.FormTitle</h5>
                </div>
                <div class="card-body pb-md-30">
                    <div class="Vertical-form">
                        <form asp-controller="CFERecord" asp-action="StoreConsumo" method="post">
                            <partial name="./Partials/ConsumoForm" model="Model.Consumo"/>
                            <div class="layout-button col-12 mt-25 justify-content-center">
                                <button type="submit" class="btn btn-primary btn-default btn-squared px-30">Guardar Consumo</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }

</div>

<style>
    .widget {
        background-color: var(--color-white);
        box-shadow: 0 5px 20px rgba(var(--box-shadow-color-rgba), 0.03);
        border-radius: 10px;
        display: inline-block;
        position: relative;
        width: 100%;
        padding: 1rem;
    }
</style>

@section scripts
{
    <script src="/assets/vendor_assets/js/select2.full.min.js"></script>
    <script>
        $(document).ready(() => {
            $('select.select2').select2();
        })
    </script>
}

Views/CFERecord/TarifasCreate.cshtml
@model SicemOperation.Entities.CFETarifa

@{
    ViewBag.Title = "Nueva Tarifa";
    ViewData["PageTitle"] = "Registrar Nueva Tarifa";
    var breadcrumbElements = new List<dynamic>();
    breadcrumbElements.Add( new { Title = "Catalogos", Route = "/CFERecord/catalogos" });
    breadcrumbElements.Add( new { Title = "Tarifas", Route = "/CFERecord/catalogos/tarifas" });
    breadcrumbElements.Add( new { Title = "Nuevo", Route = "" });
}

<partial name="PageHeader" model="@breadcrumbElements" />

<div class="row mt-4">
    <div class="border bg-white p-3 w-100 max-w-screen-xl mx-auto">
        <form asp-action="TarifasCreate" method="post">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <input asp-for="Inactivo" class="form-check-input" />
                <label asp-for="Inactivo" class="form-check-label"></label>
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
                <a asp-action="TarifasIndex" class="btn btn-secondary">Regresar</a>
            </div>
        </form>
    </div>
</div>


@*
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

Views/CFERecord/TarifasEdit.cshtml
@model SicemOperation.Entities.CFETarifa

@{
    ViewBag.Title = "Editar Tarifa";
    ViewData["PageTitle"] = "Editar Tarifa";
    var breadcrumbElements = new List<dynamic>();
    breadcrumbElements.Add( new { Title = "Catalogos", Route = "/CFERecord/catalogos" });
    breadcrumbElements.Add( new { Title = "Tarifas", Route = "/CFERecord/catalogos/tarifas" });
    breadcrumbElements.Add( new { Title = "Editar", Route = "" });
}

<partial name="PageHeader" model="@breadcrumbElements" />

<div class="row mt-4">
    <div class="border bg-white p-3 w-100 max-w-screen-xl mx-auto">
        <form asp-action="TarifasEdit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <input asp-for="Inactivo" class="form-check-input" />
                <label asp-for="Inactivo" class="form-check-label"></label>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar Cambios" class="btn btn-primary" />
                <a asp-action="TarifasIndex" class="btn btn-secondary">Regresar</a>
            </div>
        </form>
    </div>
</div>


@*
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

Views/CFERecord/TarifasIndex.cshtml
@model IEnumerable<SicemOperation.Entities.CFETarifa>
@{
    ViewBag.Title = "Catalogo Tarifas";
    ViewData["PageTitle"] = "Catalogo Tarifas";
    var breadcrumbElements = new List<dynamic>();
    breadcrumbElements.Add( new { Title = "Catalogos", Route = "/CFERecord/catalogos" });
    breadcrumbElements.Add( new { Title = "Tarifas", Route ="" });
}

<partial name="PageHeader" model="@breadcrumbElements" />

<div class="row my-2">
    <p class="border w-100 max-w-screen-xl mx-auto bg-white p-3">
        <a asp-action="TarifasCreate" class="btn btn-primary">Registar Nuevo</a>
    </p>
</div>


<div class="row my-2">
    <div class="border bg-white p-3 w-100 max-w-screen-xl mx-auto">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Inactivo</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Nombre</td>
                        <td>@(item.Inactivo ? "Yes" : "No")</td>
                        <td>
                            <a asp-action="TarifasEdit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>